### ISSUE TITLE
Would love to use. License?

### ISSUE THREAD

**Issue by oliverswitzer** [fizzed/maven-plugins#1]
Any chance that it would be possible to add an open source (MIT, etc...) license to this project?

**Comment by jjlauer** [comment]
It's maybe somewhat non-obvious, but it's declared in the pom.xml file -- it's Apache 2.

https://github.com/fizzed/maven-plugins/blob/master/pom.xml

**Comment by oliverswitzer** [comment]
@jjlauree whoops, missed that. Awesome thanks!

**Comment by oliverswitzer** [comment]
Btw are you the licensor or is fizzed inc the licensor?

**Comment by jjlauer** [comment]
Fizzed, Inc.
